unicef-polymer/etools-unicef

package-lock.json, package.json, src_ts/etools-input/etools-input.ts, src_ts/etools-input/etools-textarea.ts, src_ts/etools-input/styles/shoelace-customizations.ts
=> [ch34654]'undefined' displayed on newly added fields

src_ts/etools-input/etools-currency.ts, src_ts/etools-input/etools-input-base.ts
Fix value format for currency on ouput
=> Fix value format for currency on ouput

src_ts/etools-dropdown/SlAutocomplete.ts
[ch34664] Missing tooltips when options is selected
=> [ch34664] Missing tooltips when options is selected

src_ts/etools-dropdown/etools-dropdown-multi.ts, src_ts/etools-dropdown/etools-dropdown.ts
Fix interface definitions etools-dropdown
=> Fix interface def etools-dropdown

package-lock.json, src_ts/etools-data-table/assets/translations.ts, src_ts/etools-data-table/etools-data-table-column.ts, src_ts/etools-data-table/etools-data-table-footer.ts, src_ts/etools-data-table/etools-data-table-header.ts, src_ts/etools-data-table/etools-data-table-row.ts, src_ts/etools-data-table/etools-data-table.ts, src_ts/etools-data-table/styles/data-table-styles.ts, src_ts/etools-data-table/utils/translate.ts, src_ts/etools-info-tooltip/InfoIconTooltip.ts, src_ts/etools-table/etools-table.ts
=> Etools-data-table

.vscode/settings.json, package-lock.json, package.json, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-filters/etools-filters.ts, src_ts/etools-loading/assets/translations.ts, src_ts/etools-loading/etools-loading-mixin.ts, src_ts/etools-loading/etools-loading.ts, src_ts/etools-loading/utils/translate.ts, src_ts/etools-profile-dropdown/assets/translations.ts, src_ts/etools-profile-dropdown/etools-profile-dropdown.ts, src_ts/etools-profile-dropdown/etools-user-profile-dialog.ts, src_ts/etools-profile-dropdown/utils/translate.ts
Added etools-loading and etools-profile-dropdown + support on vscode for shoelace elements
=> Added etools-loading and etools-profile-dropdown + support on vscode for shoelace elements

.vscode/settings.json, package-lock.json, package.json, src_ts/etools-collapse/etools-collapse.ts, src_ts/etools-content-panel/etools-content-panel.ts, src_ts/etools-content-panel/styles/elevation-styles.ts, src_ts/etools-data-table/etools-data-table-row.ts, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-filters/etools-filters.ts, src_ts/etools-loading/assets/translations.ts, src_ts/etools-loading/etools-loading-mixin.ts, src_ts/etools-loading/etools-loading.ts, src_ts/etools-loading/utils/translate.ts, src_ts/etools-profile-dropdown/assets/translations.ts, src_ts/etools-profile-dropdown/etools-profile-dropdown.ts, src_ts/etools-profile-dropdown/etools-user-profile-dialog.ts, src_ts/etools-profile-dropdown/utils/translate.ts
Adding etools-content-panel & etools-collapse
=> Adding etools-content-panel & etools-collapse

.vscode/settings.json, package-lock.json, package.json, src_ts/etools-collapse/etools-collapse.ts, src_ts/etools-content-panel/etools-content-panel.ts, src_ts/etools-content-panel/styles/elevation-styles.ts, src_ts/etools-data-table/etools-data-table-row.ts, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-filters/assets/translations.ts, src_ts/etools-filters/etools-filters-styles.ts, src_ts/etools-filters/etools-filters.ts, src_ts/etools-filters/filters-helper.class.ts, src_ts/etools-filters/filters.ts, src_ts/etools-filters/utils/translate.ts, src_ts/etools-loading/assets/translations.ts, src_ts/etools-loading/etools-loading-mixin.ts, src_ts/etools-loading/etools-loading.ts, src_ts/etools-loading/utils/translate.ts, src_ts/etools-profile-dropdown/assets/translations.ts, src_ts/etools-profile-dropdown/etools-profile-dropdown.ts, src_ts/etools-profile-dropdown/etools-user-profile-dialog.ts, src_ts/etools-profile-dropdown/utils/translate.ts
=> Adding etools-filters

package-lock.json, package.json, src_ts/etools-collapse/etools-collapse.ts
=> [ch34746]Fix results structure height

src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-input/etools-currency.ts, src_ts/etools-loading/etools-loading-mixin.ts
=> [ch34731]Console & ts error

src_ts/etools-collapse/etools-collapse.ts
[ch34764] Fix etools collapse overflow issue
Merge this first in etools-date-time
=> [ch34764] Fix etools collapse overflow issue

src_ts/etools-collapse/etools-collapse.ts, src_ts/etools-date-time/assets/translations.ts, src_ts/etools-date-time/calendar-lite.ts, src_ts/etools-date-time/datepicker-lite.ts, src_ts/etools-date-time/styles/elevation-styles.ts, src_ts/etools-date-time/time-input.ts, src_ts/etools-filters/etools-filters.ts, src_ts/etools-input/etools-input.ts, src_ts/etools-input/styles/shoelace-customizations.ts
Adding etools-date-time + add allowEdit on etools-input so we can have readonly input but with normal field styling
=> Adding etools-date-time + add preventUserDirectInput on etools-input so we can have readonly input but with normal field styling

src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts, src_ts/etools-input/etools-textarea.ts, src_ts/etools-input/styles/shoelace-customizations.ts
Fix border bottom styles for input + dropdown min height when multiple items selected
=> Fix border bottom styles for input + dropdown min height when multiple items selected

src_ts/etools-dialog/EtoolsDialog.ts
=> Fix etools-dialog closing

package-lock.json, package.json, src_ts/etools-collapse/etools-collapse.ts
=> [ch34782]toogle method for etools-collapse

package-lock.json, package.json, src_ts/etools-collapse/etools-collapse.ts, src_ts/etools-dropdown/SlAutocomplete.ts
=> [ch34701]Fix dropdw eager validation

src_ts/etools-collapse/etools-collapse.ts
[ch34807] [ch34879] [ch34764] Fix collapse issue
=> [ch34807] [ch34879] [ch34764] Fix collapse issue

src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-dropdown/SlAutocomplete.ts
=> [ch34704]Fix empty dropdown on deselect by click then cancel

src_ts/etools-input/etools-currency.ts, src_ts/etools-input/etools-input.ts, src_ts/etools-input/etools-textarea.ts, src_ts/etools-input/styles/shoelace-customizations.ts
[ch34889] Date component - Validation not visible on UI + applied same logic for etools-textarea
=> [ch34889] Date component - Validation not visible on UI + applied same logic for etools-textarea

src_ts/etools-collapse/etools-collapse.ts
[ch34879][ch34917][ch34764] Fixes for etools-collapse
=> [ch34879][ch34917][ch34764] Fixes for etools-collapse

src_ts/etools-loading/etools-loading-mixin.ts, src_ts/etools-loading/etools-loading.ts
=> Lint issues

src_ts/etools-date-time/calendar-lite.ts
=> [ch34977]Fix dt translation

src_ts/etools-filters/etools-filters.ts
=> [ch34943]Filters links color not in sync with app theme

src_ts/etools-dropdown/SlAutocomplete.ts
=> [ch35036Fix can't reselect an item after cancel

src_ts/etools-dropdown/SlAutocomplete.ts
=> [ch34944]Dropdown close btn can not be activated with enter

src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts
=> [ch35094]Change focus brightness

src_ts/etools-toasts/etools-toasts.ts
[ch35138] Move etools toast to etools-unicef & migrate to shoelace
=> Move etools toast to etools-unicef & migrate to shoelace

package-lock.json, package.json, src_ts/etools-input/etools-textarea.ts, src_ts/etools-toasts/etools-toasts.ts
Added textarea max rows in order to drop the function ulity from etools-modules-common
=> Added textarea max rows in order to drop the function ulity from etools-modules-common

package-lock.json, package.json, src_ts/etools-app-selector/etools-app-selector.ts, src_ts/etools-app-selector/utils/translate.ts, src_ts/etools-collapse/etools-collapse.ts, src_ts/etools-date-time/calendar-lite.ts, src_ts/etools-date-time/datepicker-lite.ts, src_ts/etools-date-time/time-input.ts, src_ts/etools-dropdown/etools-dropdown-multi.ts, src_ts/etools-dropdown/etools-dropdown.ts, src_ts/etools-icon-button/etools-icon-button.ts, src_ts/etools-icons/etools-icon.ts, src_ts/etools-profile-dropdown/etools-profile-dropdown.ts, src_ts/etools-profile-dropdown/etools-user-profile-dialog.ts
=> Linting and version

package-lock.json, package.json, src_ts/etools-dropdown/SlAutocomplete.ts
=> Remove packages, new version

src_ts/etools-media-query/etools-media-query.ts
[ch35098] Replace iron-media-query
=> [ch35098] Replace iron-media-query

package-lock.json, package.json, src_ts/etools-media-query/etools-media-query.ts
=> Linting & Version 1.0.0-rc.21

package-lock.json, package.json, src_ts/etools-icons/etools-icons.ts
=> Fix path issue for icons

src_ts/etools-app-layout/app-drawer-layout.ts, src_ts/etools-app-layout/app-drawer.ts, src_ts/etools-app-layout/app-header-layout.ts, src_ts/etools-app-layout/app-header.ts, src_ts/etools-app-layout/app-toolbar.ts
[ch35140] Replace polymer app-layout components with Lit alternatives
=> [ch35140] Replace polymer app-layout components with Lit alternatives

package-lock.json, package.json, src_ts/etools-app-layout/app-drawer.ts
=> 1.0.0-rc.23 version, lintfix

package-lock.json, package.json, tsconfig.json
Version rc.26, typescript helpers import
=> Version rc.26

package-lock.json, package.json, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-filters/etools-filters-styles.ts
[ch35301] PMP & ePD shoelace migration issues 3
=> [ch35301] PMP & ePD shoelace migration issues 3

src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/etools-filters/etools-filters.ts, src_ts/etools-input/etools-input-base.ts, src_ts/etools-input/etools-input.ts
Adding missing shoelace properties to input base & hide buttons inside etools-dialog that have property hidden + fix dropdown error for reading filter of undefined + make search filter clearable
[ch35301] [ch35261]
=> Adding missing shoelace properties to input base & hide buttons inside etools-dialog that have property hidden

package-lock.json, package.json, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/styles/button-styles.ts
[ch35333] Clean-up, refactor, fix buttons
=> [ch35333] Clean-up, refactor, fix buttons

src_ts/etools-date-time/calendar-lite.ts, src_ts/etools-dialog/EtoolsDialog.ts
[ch35358] Fix dialog delete button
=> [ch35358] Fix dialog delete button

src_ts/etools-input/styles/shoelace-customizations.ts
=> Style issues char counter

package-lock.json, package.json, src_ts/etools-dialog/EtoolsDialog.ts
=> RC30 + lint

src_ts/etools-date-time/calendar-lite.ts, src_ts/styles/button-styles.ts
[ch35394] Calendar fix, button styles update
=> [ch35394] Calendar fix, button styles update

src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts
[ch35394] dialog header title + dropdown style issues
=> [ch35394] dialog header title + dropdown style issues

package-lock.json, src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts, src_ts/etools-dropdown/styles/sl-autocomplete-styles.ts, src_ts/etools-input/etools-input-base.ts, src_ts/etools-input/etools-input.ts, src_ts/etools-input/styles/shoelace-customizations.ts, src_ts/etools-toasts/etools-alert.ts, src_ts/etools-upload/etools-upload.ts
[ch35560] PMP & ePD shoelace migration issues 7
=> [ch35560] PMP & ePD shoelace migration issues 7

package-lock.json, package.json, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/etools-filters/etools-filters.ts
=> fixes for fm

package-lock.json, package.json, src_ts/styles/button-styles.ts
=> Update button styles

src_ts/etools-dialog/EtoolsDialog.ts
=> Fix dialog events

src_ts/etools-date-time/datepicker-lite.ts, src_ts/etools-date-time/time-input.ts, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts, src_ts/etools-dropdown/styles/sl-autocomplete-styles.ts, src_ts/etools-input/etools-input.ts, src_ts/etools-input/etools-textarea.ts, src_ts/etools-input/styles/shoelace-customizations.ts, src_ts/etools-upload/etools-upload.ts
Adapt fields state for combinations of invalid,disabled,readonly,required,focused
=> Adapt fields state for combinations of invalid,disabled,readonly,required,focused

package-lock.json, package.json, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts, src_ts/etools-input/etools-input.ts, src_ts/etools-input/etools-textarea.ts
[ch35727] FM Shoelace Migration Issues
=> [ch35727] FM Shoelace Migration Issues

package-lock.json, package.json, src_ts/etools-button/styles/button-group-styles.ts, src_ts/etools-button/styles/button-styles.ts, src_ts/etools-date-time/datepicker-lite.ts, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-input/etools-input.ts
[ch35759] [ch35830] Fm migrations 2&3
=> [ch35759] [ch35830] Fm migrations 2&3

package-lock.json, package.json, src_ts/etools-filters/filters-helper.class.ts
=> Fix filters fm

package-lock.json, package.json, src_ts/etools-date-time/calendar-lite.ts
=> Fix calendar

package-lock.json, package.json, src_ts/etools-app-selector/etools-app-selector.ts
[ch35936] Cannot close App Selector when clicking outside of the dialog
=> [ch35936] Cannot close App Selector when clicking outside of the dialog

package-lock.json, package.json, src_ts/etools-filters/etools-filters.ts
Add css parts for filter components
=> Add css parts for filter components

package-lock.json, package.json, src_ts/etools-filters/filters-helper.class.ts
[ch36008] Filters input doesn't get populated - rc.49
=> [ch36008] Filters input doesn't get populated - rc.49

package-lock.json, package.json, src_ts/etools-dropdown/SlAutocomplete.ts
[ch36030] FM Shoelace Migration 4
Published rc.51
=> [ch36030] FM Shoelace Migration 4

package-lock.json, package.json, src_ts/etools-data-table/etools-data-table-footer.ts, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-input/assets/translations.ts, src_ts/etools-input/etools-input-base.ts, src_ts/etools-input/etools-textarea.ts, src_ts/etools-table/pagination/etools-pagination.ts, src_ts/etools-upload/etools-upload-multi.ts, src_ts/etools-upload/etools-upload.ts
Improvements: Inputs translation, dialog position
=> Improvements: Inputs translation, dialog position

src_ts/etools-icons/icons/av-icons.ts, src_ts/styles/layout-styles.ts
Added Bootstrap css, optimize for small screen, mobile friendly
=> Added Bootstrap css, optimize for small screen, mobile friendly

package-lock.json, package.json, src_ts/etools-input/etools-textarea.ts
=> Fix for textarea height

package-lock.json, package.json, src_ts/etools-filters/filters.ts
Fix for filters dropdownmulti update from url params
=> Fix for filters dropdownmulti update from url params

package-lock.json, package.json, src_ts/etools-dropdown/SlAutocomplete.ts, src_ts/etools-dropdown/styles/sl-autocomplete-etools-styles.ts, src_ts/etools-dropdown/styles/sl-autocomplete-styles.ts
=> Try fix dropdown width

package-lock.json, package.json, src_ts/etools-content-panel/etools-content-panel.ts, src_ts/styles/layout-styles.ts
=> Fixes for small screens

package-lock.json, package.json, src_ts/etools-button/styles/button-styles.ts, src_ts/etools-dialog/EtoolsDialog.ts, src_ts/etools-input/etools-input-base.ts
[ch36789] Safari fixes, FM Issues  iPhone & iPad
=> [ch36789] Safari fixes, FM Issues  iPhone & iPad

package-lock.json, package.json, src_ts/etools-profile-dropdown/etools-profile-dropdown.ts, src_ts/etools-upload/etools-file.ts
Added etools-file component (used in PRP)
=> WIP!!!   Added etools-file component (used in PRP)

package-lock.json, package.json, src_ts/etools-table/etools-table.ts
=> [ch38928] AMP dev issues
